### ISSUE TITLE
Conflict with Demeter

### ISSUE THREAD

**Issue by Neubulae** [TerraformersMC/Traverse#24] opened 2020-05-15 11:30 UTC
https://pastebin.com/MRFp7R66
https://github.com/Wtoll/demeter/issues/14

**Comment by Neubulae** [comment] 2020-05-15 11:36
[crash-2020-05-15_19.26.08-client.txt](https://github.com/TerraformersMC/Traverse/files/4634086/crash-2020-05-15_19.26.08-client.txt)

**Comment by Linguardium** [comment] 2020-05-17 04:51
see https://github.com/TerraformersMC/Terraform/issues/10

**Comment by NeusFear** [comment] 2020-05-24 14:27
duplicate of https://github.com/TerraformersMC/Terraform/issues/10

**Closed as completed by NeusFear** 2020-05-24 14:27 UTC
Labels: duplicate
