### ISSUE TITLE
Leaf Blocks instead of Saplings

### ISSUE THREAD

**Issue by ghost** [TerraformersMC/Traverse#2] opened 2019-07-27 16:49 UTC
If I chop down a colored Autumn Woods Tree I get Leaf blocks instead of saplings
I'm playing the the latest fabric version of your mod.

**Comment by coderbot16** [comment] 2019-07-27 17:01
Bug reproduced, it will be fixed shortly. Due to a botched copy / paste and find + replace: https://github.com/TerraformersMC/Traverse/blob/1.14.4/src/main/resources/data/traverse/loot_tables/blocks/orange_autumnal_leaves.json#L24

(p**red**icate got changed to p**orange**icate which breaks everything)

**Comment by coderbot16** [comment] 2019-07-27 18:02
Fixed in 2.0.4 (https://github.com/TerraformersMC/Traverse/commit/b140ec8c8183931c39afd4b61b0c23a3832f7a2c)

**Closed as completed by coderbot16** 2019-07-27 18:02 UTC
Labels: bug, implemented

**Comment by ghost** [comment] 2019-07-28 11:01
All works fine now.
Thank you for the fast response

**Comment by coderbot16** [comment] 2019-07-28 13:38
You're welcome! Thanks for reporting :)
